# Funding

If Modformer is useful to you, please consider contributing through GitHub sponsorships. Of course, if you'd rather contribute in other ways, that's equally welcome. And if you're not in a position to contribute at all, but just want to show support? A message or a tweet is always gratefully received. Thanks!

github: [kolektiv]
