[workspace]
members = [
    # Core
    "crates/core/cli",
    "crates/core/core",
    "crates/core/traits",

    # Modules
    "crates/modules/fs",

    # Example
    "example/site_builder",
]

[profile.release]
lto = "fat"
opt-level = "s"
