[workspace]
members = [
    # Crates (compiled as platform-native)
    "crates/modformer_cli",
    "crates/modformer_core",

    # Modules (compiled as wasm32-wasi)
    "modules/modformer_fs",
]

[profile.release]
lto = "fat"
opt-level = "s"
