[workspace]
members = [
    # Core
    "crates/modformer",
    "crates/modformer_cli",
    "crates/modformer_model",
    "crates/modformer_transformer",

    # Modules
    "crates/modules/modformer_fs",

    # Example
    "example/site_builder",
]

[profile.release]
lto = "fat"
opt-level = "s"
