[workspace]
members = [
    # Core
    "crates/modformer_cli",
    "crates/modformer_core",

    # Modules
    "crates/modformer_fs_reader",
    "crates/modformer_fs_writer",
]

[profile.release]
lto = "fat"
opt-level = "s"
