[package]
name = "modformer_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "3.0", features = ["derive"] }
modformer_core = { path = "../core" }
modformer_traits = { path = "../traits" }
